# Get all books
GET http://localhost:3000/library/books
Accept: application/json

###

# Get a single book by ID
GET http://localhost:3000/library/books
Accept: application/json

###

# Create multiple or single books
POST http://localhost:3000/library/books
Content-Type: application/json

{
   "bookTitle": "Things Fall Apart",
    "author": "Chinua Achebe",
    "publisher": "Heinemann",
    "publicationYear": 1813,
    "shelveLocation": "Classic 456",
    "genre": "Classic Literature",
    "copiesAvailable": 65
}

###

# Update a book by ID (partial update)
PUT http://localhost:3000/library/books
Content-Type: application/json

{
  "bookTitle": "Things Fall Apart",
  "author": "Chinua Achebe",
  "publisher": "Heinemann",
  "publicationYear": 1813,
  "shelveLocation": "Classic 456",
  "genre": "Classic Literature",
  "copiesAvailable": 65
}

###

# Delete a book by ID
DELETE http://localhost:3000/library/books/67e8b7cc0dc884bda8a873a5
Accept: application/json