# Get all books
GET http://localhost:3000/library/books
Accept: application/json

###

# Get a single book by ID
GET http://localhost:3000/library/books/67e9d792e72212ae72999362
Accept: application/json

###

# Create a single book
POST http://localhost:3000/library/books
Content-Type: application/json

{
    "bookTitle": "The Return of Ikenga",
    "author": "Chukwuemeka Ohuka",
    "publisher": "Macmillan Nigeria",
    "publicationYear": 1980,
    "shelveLocation": "Classic 456",
    "genre": "Classic Literature",
    "copiesAvailable": 2
}

###

# Borrow a book by a student
POST http://localhost:3000/library/books/67ee9cd522d1dbe195f2cfdd/borrow
Content-Type: application/json

{
    "borrowerId": "67e9e2850d65edefaa323d59",
    "borrowerType": "Student"
}

###

# Return a borrowed book
POST http://localhost:3000/library/books/67ee9cd522d1dbe195f2cfdd/return
Content-Type: application/json

{
    "borrowerId": "67e6bda6762b489499bd621d"
}
###

# Update a book by ID (partial update)
PUT http://localhost:3000/library/books/67e8b7cc0dc884bda8a873a5
Content-Type: application/json

{
    "copiesAvailable": 60
}

###

# Delete a book by ID
DELETE http://localhost:3000/library/books/67e8b7cc0dc884bda8a873a5
Accept: application/json