# Get all players
GET http://localhost:3000/player
Accept: application/json

###

# Get a single player by ID
GET http://localhost:3000/player
Accept: application/json

###

# Create multiple or single players
POST http://localhost:3000/player
Content-Type: application/json

{
    
}

###

# Update a player by ID (partial update)
PUT http://localhost:3000/player
Content-Type: application/json

{
  "lastName": "Island",
  "age": 27
}

###

# Delete a player by ID
DELETE http://localhost:3000/player
Accept: application/json