# Get all students
GET http://localhost:3000/student
Accept: application/json

###

# Get a single student by ID
GET http://localhost:3000/student/67eea7f9aac6b8ab2c63bf4f
Accept: application/json

###

# Create multiple or single students
POST http://localhost:3000/student
Content-Type: application/json

{
    "firstName": "Jennifer",
    "lastName": "Lopez",
    "gender": "Female",
    "age": 25,
    "favoriteSubject": "Biology",
    "grade": "C+",
    "email": "jennifer@example.com"
}

###

# Update a student by ID (partial update)
PUT http://localhost:3000/student/67e6c038762b489499bd6224
Content-Type: application/json

{
  "favoriteSubject": "Math"
}


###

# Delete a student by ID
DELETE http://localhost:3000/student/67e9c2bbc30f038ccdc43a18
Accept: application/json